/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as StoreRouteImport } from './routes/store'
import { Route as PacerRouteImport } from './routes/pacer'
import { Route as FormRouteImport } from './routes/form'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DbRouteImport } from './routes/db'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTodosRouteImport } from './routes/api.todos'
import { Route as ApiExtractRouteImport } from './routes/api.extract'
import { Route as ApiChatRouteImport } from './routes/api.chat'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const PacerRoute = PacerRouteImport.update({
  id: '/pacer',
  path: '/pacer',
  getParentRoute: () => rootRouteImport,
} as any)
const FormRoute = FormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DbRoute = DbRouteImport.update({
  id: '/db',
  path: '/db',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTodosRoute = ApiTodosRouteImport.update({
  id: '/api/todos',
  path: '/api/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractRoute = ApiExtractRouteImport.update({
  id: '/api/extract',
  path: '/api/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/db': typeof DbRoute
  '/demo': typeof DemoRoute
  '/form': typeof FormRoute
  '/pacer': typeof PacerRoute
  '/store': typeof StoreRoute
  '/todos': typeof TodosRoute
  '/api/chat': typeof ApiChatRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/todos': typeof ApiTodosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/db': typeof DbRoute
  '/demo': typeof DemoRoute
  '/form': typeof FormRoute
  '/pacer': typeof PacerRoute
  '/store': typeof StoreRoute
  '/todos': typeof TodosRoute
  '/api/chat': typeof ApiChatRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/todos': typeof ApiTodosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/db': typeof DbRoute
  '/demo': typeof DemoRoute
  '/form': typeof FormRoute
  '/pacer': typeof PacerRoute
  '/store': typeof StoreRoute
  '/todos': typeof TodosRoute
  '/api/chat': typeof ApiChatRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/todos': typeof ApiTodosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/db'
    | '/demo'
    | '/form'
    | '/pacer'
    | '/store'
    | '/todos'
    | '/api/chat'
    | '/api/extract'
    | '/api/todos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/db'
    | '/demo'
    | '/form'
    | '/pacer'
    | '/store'
    | '/todos'
    | '/api/chat'
    | '/api/extract'
    | '/api/todos'
  id:
    | '__root__'
    | '/'
    | '/db'
    | '/demo'
    | '/form'
    | '/pacer'
    | '/store'
    | '/todos'
    | '/api/chat'
    | '/api/extract'
    | '/api/todos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DbRoute: typeof DbRoute
  DemoRoute: typeof DemoRoute
  FormRoute: typeof FormRoute
  PacerRoute: typeof PacerRoute
  StoreRoute: typeof StoreRoute
  TodosRoute: typeof TodosRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiExtractRoute: typeof ApiExtractRoute
  ApiTodosRoute: typeof ApiTodosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacer': {
      id: '/pacer'
      path: '/pacer'
      fullPath: '/pacer'
      preLoaderRoute: typeof PacerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/db': {
      id: '/db'
      path: '/db'
      fullPath: '/db'
      preLoaderRoute: typeof DbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/todos': {
      id: '/api/todos'
      path: '/api/todos'
      fullPath: '/api/todos'
      preLoaderRoute: typeof ApiTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract': {
      id: '/api/extract'
      path: '/api/extract'
      fullPath: '/api/extract'
      preLoaderRoute: typeof ApiExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DbRoute: DbRoute,
  DemoRoute: DemoRoute,
  FormRoute: FormRoute,
  PacerRoute: PacerRoute,
  StoreRoute: StoreRoute,
  TodosRoute: TodosRoute,
  ApiChatRoute: ApiChatRoute,
  ApiExtractRoute: ApiExtractRoute,
  ApiTodosRoute: ApiTodosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
